openapi: 3.0.1
info:
  title: Api1
  description: API Definition of Api1
  version: 1.0.0
servers:
- url: http://localhost:8290/api
paths:
  /categories/{category}/reserve:
    post:
      parameters:
      - name: category
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
